version: '3'
services:

  mysql57:
    image: mysql:5.7
    restart: unless-stopped
    container_name: kristjan-test-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"